Repository Techeer-H/backend, pull requests merged in 2024-01, with the labels that each got.

#3 2 setting/basic setting
  backend/Dockerfile
  backend/backend/__init__.py
  backend/backend/asgi.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/docker-compose.yml
  backend/manage.py
  backend/requirements.txt
Labels: Setting

#7 Setting
  .gitignore
  backend/analysis/__init__.py
  backend/analysis/admin.py
  backend/analysis/apps.py
  backend/analysis/migrations/__init__.py
  backend/analysis/models.py
  backend/analysis/tests.py
  backend/analysis/urls.py
  backend/analysis/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/docker-compose.yml
  backend/feedback/__init__.py
  backend/feedback/admin.py
  backend/feedback/apps.py
  backend/feedback/migrations/__init__.py
  backend/feedback/models.py
  backend/feedback/tests.py
  backend/feedback/urls.py
  backend/feedback/views.py
  backend/requirements.txt
  backend/student/__init__.py
  backend/student/admin.py
  backend/student/apps.py
  backend/student/migrations/__init__.py
  backend/student/models.py
  backend/student/tests.py
  backend/student/urls.py
  backend/student/views.py
  backend/user/__init__.py
  backend/user/admin.py
  backend/user/apps.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/tests.py
  backend/user/urls.py
  backend/user/views.py
Labels: Setting

#17 fix: user app API 수정 및 cdd 깨짐 해결
  .gitignore
  backend/backend/settings.py
  backend/backend/urls.py
  backend/docker-compose.yml
  backend/feedback/urls.py
  backend/student/models.py
  backend/student/serializers.py
  backend/student/urls.py
  backend/user/models.py
  backend/user/serializers.py
  backend/user/urls.py
  backend/user/views.py
Labels: Fix

#19 fix: swagger 수정, API 2차 수정
  backend/feedback/urls.py
  backend/feedback/views.py
  backend/student/views.py
Labels: Fix

#21 feat: User, Analysis Views에 Swagger 작성
  backend/analysis/views.py
  backend/feedback/admin.py
  backend/user/views.py
Labels: Feature

#24 fix: CORS 에러 해결 및 Swagger 수정
  backend/backend/settings.py
  backend/feedback/urls.py
  backend/feedback/views.py
  backend/requirements.txt
  backend/student/urls.py
  backend/student/views.py
  backend/user/views.py
Labels: Fix

#26 fix:성적등록 API 수정, 성적 type enum 등록, 학생 조회 API 수정
  backend/student/models.py
  backend/student/views.py
  backend/user/views.py
Labels: Fix

#29 11 feat/redis,celery
  backend/analysis/admin.py
  backend/analysis/models.py
  backend/analysis/serializers.py
  backend/analysis/tasks.py
  backend/analysis/views.py
  backend/backend/__init__.py
  backend/backend/celery.py
  backend/backend/settings.py
  backend/docker-compose.yml
  backend/requirements.txt
  backend/user/views.py
Labels: Feature

#31 fix:analysis import 주석, student 조회API 수정
  backend/analysis/admin.py
  backend/analysis/tasks.py
  backend/analysis/views.py
  backend/nginx/nginx.conf
  backend/student/views.py
Labels: Fix

#35 feat: Prometheus, Grafana로 Django Server 모니터링. API Response 대기 90초로 수정
  backend/alertmanager/alertmanager.yml
  backend/backend/settings.py
  backend/backend/urls.py
  backend/docker-compose.yml
  backend/prometheus/alert.rules
  backend/prometheus/prometheus.yml
  backend/requirements.txt
Labels: Feature, Fix

#37 fix:score,favorit API 수정
  backend/prometheus/prometheus.yml
  backend/student/views.py
  backend/user/views.py
Labels: Fix
